# Generated by Django 4.2 on 2024-01-28 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('umsebenzi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
